DELETE FROM employees;

INSERT INTO employees (company_id, first_name, last_name, role, department) VALUES
                                                                                (1, 'Rachel', 'Green', 'ADMIN', 'MANAGEMENT'),
                                                                                (1, 'Ross', 'Geller', 'HR', 'HR'),
                                                                                (1, 'Monica', 'Geller', 'HR', 'HR'),
                                                                                (1, 'Chandler', 'Bing', 'HR', 'HR'),
                                                                                (1, 'Joey', 'Tribbiani', 'EMPLOYEE', 'DEVELOPMENT'),
                                                                                (1, 'Phoebe', 'Buffay', 'EMPLOYEE', 'DEVELOPMENT'),
                                                                                (1, 'Gunther', 'Central', 'EMPLOYEE', 'OPERATIONS'),
                                                                                (1, 'Janice', 'Hosenstein', 'EMPLOYEE', 'OPERATIONS'),
                                                                                (1, 'Mike', 'Hannigan', 'EMPLOYEE', 'DEVELOPMENT'),
                                                                                (1, 'David', 'Scientist', 'EMPLOYEE', 'DEVELOPMENT'),
                                                                                (1, 'Ben', 'Geller', 'EMPLOYEE', 'DEVELOPMENT'),
                                                                                (1, 'Carol', 'Willick', 'EMPLOYEE', 'DEVELOPMENT'),
                                                                                (1, 'Susan', 'Bunch', 'EMPLOYEE', 'OPERATIONS'),
                                                                                (1, 'Emily', 'Waltham', 'EMPLOYEE', 'OPERATIONS'),
                                                                                (1, 'Richard', 'Burke', 'EMPLOYEE', 'OPERATIONS'),
                                                                                (2, 'Jerry', 'Seinfeld', 'ADMIN', 'MANAGEMENT'),
                                                                                (2, 'George', 'Costanza', 'HR', 'HR'),
                                                                                (2, 'Elaine', 'Benes', 'HR', 'HR'),
                                                                                (2, 'Cosmo', 'Kramer', 'HR', 'HR'),
                                                                                (2, 'Newman', 'Postman', 'EMPLOYEE', 'OPERATIONS'),
                                                                                (2, 'Frank', 'Costanza', 'EMPLOYEE', 'OPERATIONS'),
                                                                                (2, 'Estelle', 'Costanza', 'EMPLOYEE', 'OPERATIONS'),
                                                                                (2, 'David', 'Puddy', 'EMPLOYEE', 'DEVELOPMENT'),
                                                                                (2, 'Kenny', 'Bania', 'EMPLOYEE', 'DEVELOPMENT'),
                                                                                (2, 'Jackie', 'Chiles', 'EMPLOYEE', 'DEVELOPMENT'),
                                                                                (2, 'Sue', 'Mischke', 'EMPLOYEE', 'DEVELOPMENT'),
                                                                                (2, 'Morty', 'Seinfeld', 'EMPLOYEE', 'OPERATIONS'),
                                                                                (2, 'Helen', 'Seinfeld', 'EMPLOYEE', 'OPERATIONS'),
                                                                                (2, 'Uncle', 'Leo', 'EMPLOYEE', 'OPERATIONS'),
                                                                                (2, 'Babu', 'Bhatt', 'EMPLOYEE', 'OPERATIONS');